### ISSUE TITLE
Ultimaker Cura 5.6.0 import error

### ISSUE THREAD

**Issue by Tarasus** [mvennen/Elegoo-Neptune-4-Plus-Cura-Profile#1]
On fresh start it gives error message 

> Your configuration seems to be corrupt. Something seems to be wrong with the following profiles:
> - elegoo_extruder_0 #2
> - elegoo_extruder_0 #2_user
> Would you like to reset to factory defaults? Reset will remove all your current printers and profiles.

stderr.log gives
`

[35m2024-01-04 22:57:59,783[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)[0m
[35m2024-01-04 22:57:59,783[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: Exception: Error in the format of container elegoo_extruder_0 #2: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)[0m
[35m2024-01-04 22:57:59,784[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: Traceback (most recent call last):[0m
[35m2024-01-04 22:57:59,784[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:   File "UM\Settings\ContainerRegistry.py", line 224, in findContainers[0m
[35m2024-01-04 22:57:59,785[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:     new_container = provider.loadContainer(metadata["id"])[0m
[35m2024-01-04 22:57:59,785[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:   File "C:\Program Files\UltiMaker Cura 5.6.0\share\uranium\plugins\LocalContainerProvider\LocalContainerProvider.py", line 84, in loadContainer[0m
[35m2024-01-04 22:57:59,785[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:     container.deserialize(f.read(), file_path)[0m
[35m2024-01-04 22:57:59,786[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:   File "cura\Settings\ExtruderStack.py", line 171, in deserialize[0m
[35m2024-01-04 22:57:59,786[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:     super().deserialize(contents, file_name)[0m
[35m2024-01-04 22:57:59,786[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:   File "cura\Settings\CuraContainerStack.py", line 309, in deserialize[0m
[35m2024-01-04 22:57:59,787[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:     serialized = super().deserialize(serialized, file_name)[0m
[35m2024-01-04 22:57:59,787[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:   File "UM\Settings\ContainerStack.py", line 430, in deserialize[0m
[35m2024-01-04 22:57:59,787[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]:     raise ContainerFormatError("When trying to deserialize %s, we received an unknown container ID (%s)" % (self.getId(), container_id))[0m
[35m2024-01-04 22:57:59,788[0m - [31mERROR[0m - [37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: UM.Settings.ContainerFormatError.ContainerFormatError: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)[0m

`

[stderr.log](https://github.com/mvennen/Elegoo-Neptune-4-Plus-Cura-Profile/files/13834885/stderr.log)

**Comment by Dirk1973** [comment]
> On fresh start it gives error message
> 
> > Your configuration seems to be corrupt. Something seems to be wrong with the following profiles:
> > 
> > * elegoo_extruder_0 #2
> > * elegoo_extruder_0 #2_user
> >   Would you like to reset to factory defaults? Reset will remove all your current printers and profiles.
> 
> stderr.log gives `
> 
> �[35m2024-01-04 22:57:59,783�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)�[0m �[35m2024-01-04 22:57:59,783�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: Exception: Error in the format of container elegoo_extruder_0 #2: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)�[0m �[35m2024-01-04 22:57:59,784�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: Traceback (most recent call last):�[0m �[35m2024-01-04 22:57:59,784�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: File "UM\Settings\ContainerRegistry.py", line 224, in findContainers�[0m �[35m2024-01-04 22:57:59,785�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: new_container = provider.loadContainer(metadata["id"])�[0m �[35m2024-01-04 22:57:59,785�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: File "C:\Program Files\UltiMaker Cura 5.6.0\share\uranium\plugins\LocalContainerProvider\LocalContainerProvider.py", line 84, in loadContainer�[0m �[35m2024-01-04 22:57:59,785�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: container.deserialize(f.read(), file_path)�[0m �[35m2024-01-04 22:57:59,786�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: File "cura\Settings\ExtruderStack.py", line 171, in deserialize�[0m �[35m2024-01-04 22:57:59,786�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: super().deserialize(contents, file_name)�[0m �[35m2024-01-04 22:57:59,786�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: File "cura\Settings\CuraContainerStack.py", line 309, in deserialize�[0m �[35m2024-01-04 22:57:59,787�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: serialized = super().deserialize(serialized, file_name)�[0m �[35m2024-01-04 22:57:59,787�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: File "UM\Settings\ContainerStack.py", line 430, in deserialize�[0m �[35m2024-01-04 22:57:59,787�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: raise ContainerFormatError("When trying to deserialize %s, we received an unknown container ID (%s)" % (self.getId(), container_id))�[0m �[35m2024-01-04 22:57:59,788�[0m - �[31mERROR�[0m - �[37m[MainThread] UM.Settings.ContainerRegistry.findContainers [226]: UM.Settings.ContainerFormatError.ContainerFormatError: When trying to deserialize elegoo_extruder_0 #2, we received an unknown container ID (elegoo_extruder_0 #2_user)�[0m
> 
> `
> 
> [stderr.log](https://github.com/mvennen/Elegoo-Neptune-4-Plus-Cura-Profile/files/13834885/stderr.log)

come si risolve?

**Comment by Tarasus** [comment]
> come si risolve?

Haven't resolved it yet, just using the older elegoo version of cura (4.8.0), since it gets better prints for me.
